# -*- coding: utf-8 -*-
"""Assignment 6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ttmmzxYpa2DI2JH-NmK3VDN505B8_t2G

# Assignment 7
"""
import numpy as np

# problem 1
first = np.zeros(15)
second = np.ones(15)
print('\nProblem 1 output:', np.concatenate((first, second, first)))

arr_problem_2 = np.arange(5, 106)
print('\nProblem 2 output:', arr_problem_2)

arr_problem_3 = np.random.rand(10)
print('\nProblem 3 output:', arr_problem_3)

arr_problem_4 = np.arange(12).reshape(3, 4)
print('\nProblem 4 output:', arr_problem_4[0])

arr_problem_5 = np.arange(5, 56)
print('\nProblem 5 output:', arr_problem_5[1:-1])

arr_problem_6 = np.ones(100).reshape(10, 10)
arr_problem_6[1:-1, 1:-1] = 0
print('Problem 6 output:', arr_problem_6)

arr_problem_7a = np.arange(10)
arr_problem_7b = np.arange(10)
arr_problem_7a * arr_problem_7b

np.savez_compressed('arrays.npz', arr_problem_4=arr_problem_4,
                    arr_problem_5=arr_problem_5)
data = np.load('arrays.npz')
print('\nProblem 7 Output:')
print('Array 1 :\n', data['arr_problem_4'])
print('Array 2 :\n', data['arr_problem_5'])
